## Метрики эффективности моделей машинного обучения
### Цель работы
Научиться измерять эффективность моделей машинного обучения с помощью метрик, вибирать метрики исходя из задачи, разбивать датасет на обучающую и тестовую подвыборки.

### Содержание работы
1) Загрузите данные о вероятности развития сердечного приступа, прилагающийся к этой работе (heart.csv).
2) Обучите на этих данных простую модель логистической регрессии и выведите метрику точности (accuracy).
3) Разделите датасет на две части - первую половину используйте для обучения, а вторую - для оценки точности. Сравните значения метрик.
4) Разделите датасет на две части случайным образом. Повторите анализ.
5) Разделите датасет с помощью библиотечной функции. Повторите анализ несколько раз.
6) Постройте матрицу классификации и отчет о классификации для обученной модели для обучающей и тестовой выборок. Проинтерпретируйте полученные значения.
7) Подсчитайте для построенной модели значение всех метрик эффективности классификации на тестовой и обучающей выборках. Нужно использовать следующие метрики: accuracy, precision, recall, f1.

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

### 1. Загрузите данные о вероятности развития сердечного приступа, прилагающийся к этой работе (heart.csv).

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/koroteevmv/ML_course/refs/heads/main/ML4.1%20metrics/data/heart.csv')
data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

### 2. Обучите на этих данных простую модель логистической регрессии и выведите метрику точности (accuracy).

In [3]:
from sklearn.linear_model import LinearRegression
X = data.drop('output', axis=1)
y = data['output']
lr_model = LinearRegression()
lr_model.fit(X, y)

LinearRegression()

In [4]:
lr_model.score(X, y)

0.5175499644256842

### 3. Разделите датасет на две части - первую половину используйте для обучения, а вторую - для оценки точности. Сравните значения метрик.

In [5]:
x_train, y_train = X[:200], y[:200]
x_train.shape, y_train.shape

((200, 13), (200,))

In [6]:
x_test, y_test = X[200:], y[200:]
x_test.shape, y_test.shape

((103, 13), (103,))

In [7]:
lr_model.fit(x_train, y_train)

LinearRegression()

In [8]:
lr_model.score(x_train, y_train)

0.45405804018236195

In [9]:

lr_model.predict(x_test)

array([ 0.75194431,  0.1589634 ,  0.45760619,  0.6185906 , -0.20536379,
        0.63463611,  0.34723006,  0.31155265,  0.4546555 ,  0.6752418 ,
        0.73309023,  0.14842541,  0.56768794,  0.55630577,  0.44877022,
        0.26813972,  0.73318975,  0.10733601,  0.21077554,  0.44121948,
        0.01226233, -0.07190108,  0.8527078 ,  0.00574668,  0.21386137,
        0.33361744,  0.41562629,  0.44133546,  0.95184152,  0.61487406,
        1.0651674 ,  0.23974811,  0.39561276,  0.22404809,  0.14463121,
        0.53857414,  0.54039987,  0.37441532,  0.49652804,  0.59427433,
        0.40497086,  0.88486639,  0.45384374,  0.33911121,  0.40688837,
        0.6005157 ,  0.25104764,  0.70110343,  0.79235655,  0.38460263,
       -0.13155312,  0.21930841,  0.39190055,  0.35642161,  1.05394538,
        0.3062811 ,  0.03386762,  0.45263146,  0.73724523,  0.57409542,
        0.55453266,  0.8048266 ,  0.15974414,  0.53138964,  0.53636692,
        0.61174202,  0.49997098,  0.63558869,  0.0727705 ,  0.26

In [10]:
lr_model.score(x_test, y_test)

0.0

### 4. Разделите датасет на две части случайным образом. Повторите анализ.

In [11]:
N = int(X.shape[0] * 0.8)

x_train, y_train, x_test, y_test = X[:N], y[:N], X[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [12]:
lr_model_fn = LinearRegression()
lr_model_fn.fit(x_train, y_train) 

LinearRegression()

In [13]:
lr_model_fn.score(x_train, y_train)

0.5452486098240781

In [14]:

lr_model_fn.score(x_test, y_test)

0.0

### 5. Разделите датасет с помощью библиотечной функции. Повторите анализ несколько раз.

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
lr_model_fn.fit(X_train, y_train)

LinearRegression()

In [16]:
lr_model_fn.predict(X_test)

array([ 0.4056867 ,  0.99580547, -0.08896259,  0.20600205,  0.98298822,
        0.65769766, -0.17972212,  1.13109831,  0.55656184,  0.0771052 ,
        0.74637218,  0.43588461,  0.73390482,  0.06756047,  0.65552901,
        0.17166919, -0.03051381,  0.1474383 ,  0.77576624,  0.63457202,
        0.68373637,  0.92072116,  0.25580526,  0.36738524,  0.7579919 ,
        0.35352197, -0.14538832,  1.07411363,  0.23273516,  0.82636777,
        0.70898605,  0.69502641,  0.95890063,  0.81879918,  0.93017491,
        0.11761362,  0.69117701,  0.60652647,  0.11249762,  0.61182064,
       -0.2108675 ,  0.12447616,  0.44769275,  0.91663025,  0.61951503,
        1.15084071,  0.09571379,  0.25256889,  1.14280713,  0.72160754,
        0.63584519,  0.77457814,  0.61699227,  0.6041908 ,  0.45289008,
        0.14255402,  0.35335214,  0.80242518,  0.98458307,  0.32342712,
        0.58039106])

In [17]:
lr_model_fn.score(X_train, y_train)

0.5078737677518389

In [18]:
lr_model_fn.score(X_test, y_test)

0.5238427377889393

### 6. Постройте матрицу классификации и отчет о классификации для обученной модели для обучающей и тестовой выборок. Проинтерпретируйте полученные значения.

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
y_test_pred = lr_model.predict(x_test)
y_train_pred = lr_model.predict(x_train)
y_train_pred_binary = (y_train_pred >= 0.5).astype(int)
confusion_matrix(y_train, y_train_pred_binary)

array([[ 32,  78],
       [ 21, 111]])

In [20]:
y_test_pred_binary = (y_test_pred >= 0.5).astype(int)
confusion_matrix(y_test, y_test_pred_binary)

array([[13, 15],
       [14, 19]])

In [21]:
print(classification_report(y_test, y_test_pred_binary))

              precision    recall  f1-score   support

           0       0.48      0.46      0.47        28
           1       0.56      0.58      0.57        33

    accuracy                           0.52        61
   macro avg       0.52      0.52      0.52        61
weighted avg       0.52      0.52      0.52        61



### 7. Подсчитайте для построенной модели значение всех метрик эффективности классификации на тестовой и обучающей выборках. Нужно использовать следующие метрики: accuracy, precision, recall, f1.

In [22]:
metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred_binary),
        precision_score(y_train, y_train_pred_binary),
        recall_score(y_train, y_train_pred_binary),
        f1_score(y_train, y_train_pred_binary),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred_binary),
        precision_score(y_test, y_test_pred_binary),
        recall_score(y_test, y_test_pred_binary),
        f1_score(y_test, y_test_pred_binary),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

Train      Test
Accuracy   0.590909  0.524590
Precision  0.587302  0.558824
Recall     0.840909  0.575758
F1         0.691589  0.567164

## Задания для самостоятельного выполнения
### 1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score
from sklearn.model_selection import cross_val_score

In [24]:
def train_and_evaluate_models_classification(X_train, X_test, y_train, y_test):
    models = {
        "Логистическая регрессия": LogisticRegression(max_iter=1000),
        "Метод опорных векторов (линейное ядро)": SVC(kernel='linear', probability=True),
        "Метод опорных векторов (гауссовое ядро)": SVC(kernel='rbf', probability=True),
        "Метод ближайших соседей": KNeighborsClassifier(),
        "Дерево решений": DecisionTreeClassifier(),
        "Случайный лес": RandomForestClassifier(),
        "Градиентный бустинг": GradientBoostingClassifier(),
        "Беггинг": BaggingClassifier(),
        "Многослойный перцептрон": MLPClassifier(max_iter=1000)
    }

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_pred_proba = model.predict_proba(X_test) # Берём вероятность положительного класса
        
        roc_auc = roc_auc_score(y_test, y_pred_proba, multi_class="ovr")
        accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")

        cv_score = cross_val_score(model, X_train, y_train, cv=5, scoring='f1_weighted').mean()

        print(f"{model_name}:")
        print(f"  ROC-AUC: {roc_auc:.4f}")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  F1-score: {f1:.4f}")
        print(f"  Кросс-валидация (F1-score): {cv_score:.4f}\n")

In [25]:
from sklearn.datasets import load_iris
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
classification_results = train_and_evaluate_models_classification(X_train, X_test, y_train, y_test)
print("Classification Results:")
print(classification_results)

Логистическая регрессия:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9657

Метод опорных векторов (линейное ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9574

Метод опорных векторов (гауссовое ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9477

Метод ближайших соседей:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9393

Дерево решений:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9494

Случайный лес:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9493

Градиентный бустинг:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9410

Беггинг:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9412

Многослойный перцептрон:
  ROC-AUC: 1.0000
  Accuracy: 1

### 2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [26]:
from sklearn.datasets import load_wine
wine = load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=42)
classification_results_wine = train_and_evaluate_models_classification(X_train, X_test, y_train, y_test)
print("\nMulti-class Classification Results (Wine Dataset):")
print(classification_results_wine)

/opt/conda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/conda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Логистическая регрессия:
  ROC-AUC: 1.0000
  Accuracy: 0.9722
  F1-score: 0.9722
  Кросс-валидация (F1-score): 0.9502

Метод опорных векторов (линейное ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9426

Метод опорных векторов (гауссовое ядро):
  ROC-AUC: 0.9123
  Accuracy: 0.8056
  F1-score: 0.8024
  Кросс-валидация (F1-score): 0.6027

Метод ближайших соседей:
  ROC-AUC: 0.8828
  Accuracy: 0.7222
  F1-score: 0.7222
  Кросс-валидация (F1-score): 0.6539

Дерево решений:
  ROC-AUC: 0.9521
  Accuracy: 0.9444
  F1-score: 0.9440
  Кросс-валидация (F1-score): 0.9143

Случайный лес:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9713

Градиентный бустинг:
  ROC-AUC: 0.9903
  Accuracy: 0.9444
  F1-score: 0.9440
  Кросс-валидация (F1-score): 0.9221

Беггинг:
  ROC-AUC: 1.0000
  Accuracy: 0.9722
  F1-score: 0.9718
  Кросс-валидация (F1-score): 0.9290

Многослойный перцептрон:
  ROC-AUC: 0.2384
  Accuracy: 0

/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


### 3. Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [27]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import cross_val_score

In [28]:
def train_and_evaluate_models(X_train, X_test, y_train, y_test):
    models = {
        "Линейная регрессия": LinearRegression(),
        "Гребневая регрессия": Ridge(),
        "Лассо регрессия": Lasso(),
        "ElasticNet регрессия": ElasticNet(),
        "Метод опорных векторов (без ядра)": SVR(kernel='linear'),
        "Метод опорных векторов (гауссовое ядро)": SVR(kernel='rbf'),
        "Метод опорных векторов (полиномиальное ядро)": SVR(kernel='poly'),
        "Метод ближайших соседей": KNeighborsRegressor(),
        "Многослойный перцептрон": MLPRegressor(max_iter=1000),
        "Дерево решений": DecisionTreeRegressor(),
        "Случайный лес": RandomForestRegressor(),
        "Беггинг": BaggingRegressor()
    }

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        # Метрики
        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)
        
        # Кросс-валидация - промежуточный этап оценки модели
        cv_score = cross_val_score(model, X_train, y_train, cv=5, scoring='r2').mean()

        # Выводим результаты
        print(f"{model_name}:")
        print(f"  R²: {r2:.4f}")
        print(f"  MAE: {mae:.4f}")
        print(f"  MSE: {mse:.4f}")
        print(f"  RMSE: {rmse:.4f}")
        print(f"  Кросс-валидация: {cv_score:.4f}\n")

In [29]:

diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:

train_and_evaluate_models(X_train, X_test, y_train, y_test)

Линейная регрессия:
  R²: 0.4526
  MAE: 42.7941
  MSE: 2900.1936
  RMSE: 53.8534
  Кросс-валидация: 0.4493

Гребневая регрессия:
  R²: 0.4192
  MAE: 46.1389
  MSE: 3077.4159
  RMSE: 55.4745
  Кросс-валидация: 0.3802

Лассо регрессия:
  R²: 0.3576
  MAE: 49.7303
  MSE: 3403.5757
  RMSE: 58.3402
  Кросс-валидация: 0.3238

ElasticNet регрессия:
  R²: -0.0025
  MAE: 63.7059
  MSE: 5311.2128
  RMSE: 72.8781
  Кросс-валидация: -0.0216

Метод опорных векторов (без ядра):
  R²: 0.0203
  MAE: 61.9045
  MSE: 5190.3877
  RMSE: 72.0443
  Кросс-валидация: -0.0263

Метод опорных векторов (гауссовое ядро):
  R²: 0.1821
  MAE: 56.0237
  MSE: 4333.2860
  RMSE: 65.8277
  Кросс-валидация: 0.1122

Метод опорных векторов (полиномиальное ядро):
  R²: 0.2822
  MAE: 51.6617
  MSE: 3803.0441
  RMSE: 61.6688
  Кросс-валидация: 0.1794

Метод ближайших соседей:
  R²: 0.4302
  MAE: 42.7708
  MSE: 3019.0755
  RMSE: 54.9461
  Кросс-валидация: 0.3172



/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perce

Многослойный перцептрон:
  R²: 0.3928
  MAE: 47.4576
  MSE: 3217.2729
  RMSE: 56.7210
  Кросс-валидация: 0.3783

Дерево решений:
  R²: 0.0769
  MAE: 53.2697
  MSE: 4890.5506
  RMSE: 69.9325
  Кросс-валидация: -0.0928

Случайный лес:
  R²: 0.4255
  MAE: 44.1854
  MSE: 3043.5865
  RMSE: 55.1687
  Кросс-валидация: 0.3985

Беггинг:
  R²: 0.3425
  MAE: 48.4124
  MSE: 3483.7374
  RMSE: 59.0232
  Кросс-валидация: 0.3232

